# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Letmeknow < Formula
  desc ""
  homepage "https://github.com/shohag121/LetMeKnow"
  version "0.0.2"

  on_macos do
    url "https://github.com/shohag121/LetMeKnow/releases/download/0.0.2/LetMeKnow_0.0.2_darwin_all.tar.gz"
    sha256 "020fb7f2ba95783876fa0b63cadae37f2c7c3120867bc680e622f07ffa0819e0"

    def install
      bin.install "LetMeKnow"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shohag121/LetMeKnow/releases/download/0.0.2/LetMeKnow_0.0.2_linux_arm64.tar.gz"
      sha256 "9f710445d439377d34b98be7cee7cfc3c2544d8f8a28d8d8ca41564c90c9e62b"

      def install
        bin.install "letmeknow"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/shohag121/LetMeKnow/releases/download/0.0.2/LetMeKnow_0.0.2_linux_amd64.tar.gz"
      sha256 "3257e9b8194c482c9c1d50fba2d09a437e8a2620dc8ab7bedf514bbffcb27cc3"

      def install
        bin.install "letmeknow"
      end
    end
  end
end
